<?php


namespace App\Repositories\Role;

use Illuminate\Http\Request;
use App\Repositories\BaseRepository;
use Spatie\Permission\Models\Role;

class RoleRepository extends BaseRepository
{
    public function __construct(Role $model)
    {
        parent::__construct($model);
    }

    public function all()
    {
        return $this->model->with('permissions')->get();
    }

    public function customPaginate(int $perPage, Request $request)
    {
        return $this->model->where('name', 'like', "%$request->q%")
            ->with('permissions')
            ->paginate($perPage);
    }

    public function assignPermissions($role, array $permissions)
    {
        $role->syncPermissions($permissions);
    }

    public function updatePermissions($role, array $permissions)
    {
        $role->syncPermissions($permissions);
    }

    public function fillables()
    {
        return ['name', 'title', 'guard_name'];
    }

    public function find($id)
    {
        return $this->model->with('permissions')->findOrFail($id);
    }

    public function update(array $data, $id)
    {
        parent::update($data, $id); // TODO: Change the autogenerated stub

        return $this->find($id);
    }
}
